[package]
name = "aoc-0801"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
	take-until = { git = "https://github.com/hdevalke/take-until", branch = "master" }
